api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_docs: true
    enable_entrypoint: true
    eager_loading:
        max_joins: 50 # par exemple, augmente à 50 ou plus selon besoin
    # defaults:
    #     stateless: true
    #     cache_headers:
    #         vary: ['Content-Type', 'Authorization', 'Origin']
    # formats:
    #     jsonld: ['application/ld+json']
    #     json: ['application/json']
    #     html: ['text/html']
    #     multipart: ['multipart/form-data']
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 30