api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_docs: true
    enable_entrypoint: true
    eager_loading:
        max_joins: 50 # par exemple, augmente à 50 ou plus selon besoin
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        sonld: ['application/ld+json']
        json: ['application/json']
        multipart: ['multipart/form-data']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']