vich_uploader:
    db_driver: orm
    mappings:
        Voitures:
            uri_prefix: /images/voitures
            upload_destination: '%kernel.project_dir%/public/images/voitures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
